services:
  postgresql:
    container_name: dku-postgresql
    image: postgres:alpine
    command: postgres -c max_connections=1500 -c shared_buffers=8GB -c effective_cache_size=18GB -c work_mem=32MB -c maintenance_work_mem=1GB
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - dku

volumes:
  postgresql-data:

networks:
  dku:
    external: true
