services:
  minio:
    container_name: dku-minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      VIRTUAL_HOST: minio.seongmin.dev
      VIRTUAL_PORT: ${MINIO_PORT}

    networks:
      - dku
volumes:
  minio-data:

networks:
  dku:
    external: true
