// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "publisher", Type: field.TypeString, Nullable: true},
		{Name: "quantity", Type: field.TypeInt, Default: 1},
		{Name: "borrow", Type: field.TypeInt, Default: 0},
		{Name: "cover", Type: field.TypeString},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
	}
	// BookLogsColumns holds the columns for the "book_logs" table.
	BookLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"CREATE", "UPDATE", "DELETE", "BORROW", "RETURN"}},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "book_id", Type: field.TypeInt},
		{Name: "book_title", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BookLogsTable holds the schema information for the "book_logs" table.
	BookLogsTable = &schema.Table{
		Name:       "book_logs",
		Columns:    BookLogsColumns,
		PrimaryKey: []*schema.Column{BookLogsColumns[0]},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// BookUserColumns holds the columns for the "book_user" table.
	BookUserColumns = []*schema.Column{
		{Name: "book_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// BookUserTable holds the schema information for the "book_user" table.
	BookUserTable = &schema.Table{
		Name:       "book_user",
		Columns:    BookUserColumns,
		PrimaryKey: []*schema.Column{BookUserColumns[0], BookUserColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "book_user_book_id",
				Columns:    []*schema.Column{BookUserColumns[0]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "book_user_user_id",
				Columns:    []*schema.Column{BookUserColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// BookCategoryColumns holds the columns for the "book_category" table.
	BookCategoryColumns = []*schema.Column{
		{Name: "book_id", Type: field.TypeInt},
		{Name: "category_id", Type: field.TypeInt},
	}
	// BookCategoryTable holds the schema information for the "book_category" table.
	BookCategoryTable = &schema.Table{
		Name:       "book_category",
		Columns:    BookCategoryColumns,
		PrimaryKey: []*schema.Column{BookCategoryColumns[0], BookCategoryColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "book_category_book_id",
				Columns:    []*schema.Column{BookCategoryColumns[0]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "book_category_category_id",
				Columns:    []*schema.Column{BookCategoryColumns[1]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		BookLogsTable,
		CategoriesTable,
		UsersTable,
		BookUserTable,
		BookCategoryTable,
	}
)

func init() {
	BookUserTable.ForeignKeys[0].RefTable = BooksTable
	BookUserTable.ForeignKeys[1].RefTable = UsersTable
	BookCategoryTable.ForeignKeys[0].RefTable = BooksTable
	BookCategoryTable.ForeignKeys[1].RefTable = CategoriesTable
}
