// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilcm96/dku-aegis-library/ent/booklog"
	"github.com/ilcm96/dku-aegis-library/ent/predicate"
)

// BookLogUpdate is the builder for updating BookLog entities.
type BookLogUpdate struct {
	config
	hooks    []Hook
	mutation *BookLogMutation
}

// Where appends a list predicates to the BookLogUpdate builder.
func (blu *BookLogUpdate) Where(ps ...predicate.BookLog) *BookLogUpdate {
	blu.mutation.Where(ps...)
	return blu
}

// Mutation returns the BookLogMutation object of the builder.
func (blu *BookLogUpdate) Mutation() *BookLogMutation {
	return blu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (blu *BookLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, blu.sqlSave, blu.mutation, blu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (blu *BookLogUpdate) SaveX(ctx context.Context) int {
	affected, err := blu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (blu *BookLogUpdate) Exec(ctx context.Context) error {
	_, err := blu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blu *BookLogUpdate) ExecX(ctx context.Context) {
	if err := blu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (blu *BookLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(booklog.Table, booklog.Columns, sqlgraph.NewFieldSpec(booklog.FieldID, field.TypeInt))
	if ps := blu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, blu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	blu.mutation.done = true
	return n, nil
}

// BookLogUpdateOne is the builder for updating a single BookLog entity.
type BookLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookLogMutation
}

// Mutation returns the BookLogMutation object of the builder.
func (bluo *BookLogUpdateOne) Mutation() *BookLogMutation {
	return bluo.mutation
}

// Where appends a list predicates to the BookLogUpdate builder.
func (bluo *BookLogUpdateOne) Where(ps ...predicate.BookLog) *BookLogUpdateOne {
	bluo.mutation.Where(ps...)
	return bluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bluo *BookLogUpdateOne) Select(field string, fields ...string) *BookLogUpdateOne {
	bluo.fields = append([]string{field}, fields...)
	return bluo
}

// Save executes the query and returns the updated BookLog entity.
func (bluo *BookLogUpdateOne) Save(ctx context.Context) (*BookLog, error) {
	return withHooks(ctx, bluo.sqlSave, bluo.mutation, bluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bluo *BookLogUpdateOne) SaveX(ctx context.Context) *BookLog {
	node, err := bluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bluo *BookLogUpdateOne) Exec(ctx context.Context) error {
	_, err := bluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bluo *BookLogUpdateOne) ExecX(ctx context.Context) {
	if err := bluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bluo *BookLogUpdateOne) sqlSave(ctx context.Context) (_node *BookLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(booklog.Table, booklog.Columns, sqlgraph.NewFieldSpec(booklog.FieldID, field.TypeInt))
	id, ok := bluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, booklog.FieldID)
		for _, f := range fields {
			if !booklog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != booklog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &BookLog{config: bluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bluo.mutation.done = true
	return _node, nil
}
