// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilcm96/dku-aegis-library/ent/book"
	"github.com/ilcm96/dku-aegis-library/ent/category"
	"github.com/ilcm96/dku-aegis-library/ent/predicate"
	"github.com/ilcm96/dku-aegis-library/ent/user"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (bu *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetTitle sets the "title" field.
func (bu *BookUpdate) SetTitle(s string) *BookUpdate {
	bu.mutation.SetTitle(s)
	return bu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (bu *BookUpdate) SetNillableTitle(s *string) *BookUpdate {
	if s != nil {
		bu.SetTitle(*s)
	}
	return bu
}

// SetAuthor sets the "author" field.
func (bu *BookUpdate) SetAuthor(s string) *BookUpdate {
	bu.mutation.SetAuthor(s)
	return bu
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (bu *BookUpdate) SetNillableAuthor(s *string) *BookUpdate {
	if s != nil {
		bu.SetAuthor(*s)
	}
	return bu
}

// ClearAuthor clears the value of the "author" field.
func (bu *BookUpdate) ClearAuthor() *BookUpdate {
	bu.mutation.ClearAuthor()
	return bu
}

// SetPublisher sets the "publisher" field.
func (bu *BookUpdate) SetPublisher(s string) *BookUpdate {
	bu.mutation.SetPublisher(s)
	return bu
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (bu *BookUpdate) SetNillablePublisher(s *string) *BookUpdate {
	if s != nil {
		bu.SetPublisher(*s)
	}
	return bu
}

// ClearPublisher clears the value of the "publisher" field.
func (bu *BookUpdate) ClearPublisher() *BookUpdate {
	bu.mutation.ClearPublisher()
	return bu
}

// SetQuantity sets the "quantity" field.
func (bu *BookUpdate) SetQuantity(i int) *BookUpdate {
	bu.mutation.ResetQuantity()
	bu.mutation.SetQuantity(i)
	return bu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (bu *BookUpdate) SetNillableQuantity(i *int) *BookUpdate {
	if i != nil {
		bu.SetQuantity(*i)
	}
	return bu
}

// AddQuantity adds i to the "quantity" field.
func (bu *BookUpdate) AddQuantity(i int) *BookUpdate {
	bu.mutation.AddQuantity(i)
	return bu
}

// SetRented sets the "rented" field.
func (bu *BookUpdate) SetRented(i int) *BookUpdate {
	bu.mutation.ResetRented()
	bu.mutation.SetRented(i)
	return bu
}

// SetNillableRented sets the "rented" field if the given value is not nil.
func (bu *BookUpdate) SetNillableRented(i *int) *BookUpdate {
	if i != nil {
		bu.SetRented(*i)
	}
	return bu
}

// AddRented adds i to the "rented" field.
func (bu *BookUpdate) AddRented(i int) *BookUpdate {
	bu.mutation.AddRented(i)
	return bu
}

// SetCover sets the "cover" field.
func (bu *BookUpdate) SetCover(s string) *BookUpdate {
	bu.mutation.SetCover(s)
	return bu
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (bu *BookUpdate) SetNillableCover(s *string) *BookUpdate {
	if s != nil {
		bu.SetCover(*s)
	}
	return bu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (bu *BookUpdate) AddUserIDs(ids ...int) *BookUpdate {
	bu.mutation.AddUserIDs(ids...)
	return bu
}

// AddUser adds the "user" edges to the User entity.
func (bu *BookUpdate) AddUser(u ...*User) *BookUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bu.AddUserIDs(ids...)
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (bu *BookUpdate) AddCategoryIDs(ids ...int) *BookUpdate {
	bu.mutation.AddCategoryIDs(ids...)
	return bu
}

// AddCategory adds the "category" edges to the Category entity.
func (bu *BookUpdate) AddCategory(c ...*Category) *BookUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return bu.AddCategoryIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (bu *BookUpdate) Mutation() *BookMutation {
	return bu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (bu *BookUpdate) ClearUser() *BookUpdate {
	bu.mutation.ClearUser()
	return bu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (bu *BookUpdate) RemoveUserIDs(ids ...int) *BookUpdate {
	bu.mutation.RemoveUserIDs(ids...)
	return bu
}

// RemoveUser removes "user" edges to User entities.
func (bu *BookUpdate) RemoveUser(u ...*User) *BookUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bu.RemoveUserIDs(ids...)
}

// ClearCategory clears all "category" edges to the Category entity.
func (bu *BookUpdate) ClearCategory() *BookUpdate {
	bu.mutation.ClearCategory()
	return bu
}

// RemoveCategoryIDs removes the "category" edge to Category entities by IDs.
func (bu *BookUpdate) RemoveCategoryIDs(ids ...int) *BookUpdate {
	bu.mutation.RemoveCategoryIDs(ids...)
	return bu
}

// RemoveCategory removes "category" edges to Category entities.
func (bu *BookUpdate) RemoveCategory(c ...*Category) *BookUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return bu.RemoveCategoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BookUpdate) check() error {
	if v, ok := bu.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	return nil
}

func (bu *BookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if bu.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := bu.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if bu.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := bu.mutation.Quantity(); ok {
		_spec.SetField(book.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedQuantity(); ok {
		_spec.AddField(book.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Rented(); ok {
		_spec.SetField(book.FieldRented, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedRented(); ok {
		_spec.AddField(book.FieldRented, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if bu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedUserIDs(); len(nodes) > 0 && !bu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedCategoryIDs(); len(nodes) > 0 && !bu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (buo *BookUpdateOne) SetTitle(s string) *BookUpdateOne {
	buo.mutation.SetTitle(s)
	return buo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableTitle(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetTitle(*s)
	}
	return buo
}

// SetAuthor sets the "author" field.
func (buo *BookUpdateOne) SetAuthor(s string) *BookUpdateOne {
	buo.mutation.SetAuthor(s)
	return buo
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableAuthor(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetAuthor(*s)
	}
	return buo
}

// ClearAuthor clears the value of the "author" field.
func (buo *BookUpdateOne) ClearAuthor() *BookUpdateOne {
	buo.mutation.ClearAuthor()
	return buo
}

// SetPublisher sets the "publisher" field.
func (buo *BookUpdateOne) SetPublisher(s string) *BookUpdateOne {
	buo.mutation.SetPublisher(s)
	return buo
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillablePublisher(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetPublisher(*s)
	}
	return buo
}

// ClearPublisher clears the value of the "publisher" field.
func (buo *BookUpdateOne) ClearPublisher() *BookUpdateOne {
	buo.mutation.ClearPublisher()
	return buo
}

// SetQuantity sets the "quantity" field.
func (buo *BookUpdateOne) SetQuantity(i int) *BookUpdateOne {
	buo.mutation.ResetQuantity()
	buo.mutation.SetQuantity(i)
	return buo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableQuantity(i *int) *BookUpdateOne {
	if i != nil {
		buo.SetQuantity(*i)
	}
	return buo
}

// AddQuantity adds i to the "quantity" field.
func (buo *BookUpdateOne) AddQuantity(i int) *BookUpdateOne {
	buo.mutation.AddQuantity(i)
	return buo
}

// SetRented sets the "rented" field.
func (buo *BookUpdateOne) SetRented(i int) *BookUpdateOne {
	buo.mutation.ResetRented()
	buo.mutation.SetRented(i)
	return buo
}

// SetNillableRented sets the "rented" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableRented(i *int) *BookUpdateOne {
	if i != nil {
		buo.SetRented(*i)
	}
	return buo
}

// AddRented adds i to the "rented" field.
func (buo *BookUpdateOne) AddRented(i int) *BookUpdateOne {
	buo.mutation.AddRented(i)
	return buo
}

// SetCover sets the "cover" field.
func (buo *BookUpdateOne) SetCover(s string) *BookUpdateOne {
	buo.mutation.SetCover(s)
	return buo
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableCover(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetCover(*s)
	}
	return buo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (buo *BookUpdateOne) AddUserIDs(ids ...int) *BookUpdateOne {
	buo.mutation.AddUserIDs(ids...)
	return buo
}

// AddUser adds the "user" edges to the User entity.
func (buo *BookUpdateOne) AddUser(u ...*User) *BookUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return buo.AddUserIDs(ids...)
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (buo *BookUpdateOne) AddCategoryIDs(ids ...int) *BookUpdateOne {
	buo.mutation.AddCategoryIDs(ids...)
	return buo
}

// AddCategory adds the "category" edges to the Category entity.
func (buo *BookUpdateOne) AddCategory(c ...*Category) *BookUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return buo.AddCategoryIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (buo *BookUpdateOne) Mutation() *BookMutation {
	return buo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (buo *BookUpdateOne) ClearUser() *BookUpdateOne {
	buo.mutation.ClearUser()
	return buo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (buo *BookUpdateOne) RemoveUserIDs(ids ...int) *BookUpdateOne {
	buo.mutation.RemoveUserIDs(ids...)
	return buo
}

// RemoveUser removes "user" edges to User entities.
func (buo *BookUpdateOne) RemoveUser(u ...*User) *BookUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return buo.RemoveUserIDs(ids...)
}

// ClearCategory clears all "category" edges to the Category entity.
func (buo *BookUpdateOne) ClearCategory() *BookUpdateOne {
	buo.mutation.ClearCategory()
	return buo
}

// RemoveCategoryIDs removes the "category" edge to Category entities by IDs.
func (buo *BookUpdateOne) RemoveCategoryIDs(ids ...int) *BookUpdateOne {
	buo.mutation.RemoveCategoryIDs(ids...)
	return buo
}

// RemoveCategory removes "category" edges to Category entities.
func (buo *BookUpdateOne) RemoveCategory(c ...*Category) *BookUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return buo.RemoveCategoryIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (buo *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Book entity.
func (buo *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BookUpdateOne) check() error {
	if v, ok := buo.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	return nil
}

func (buo *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if buo.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := buo.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if buo.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := buo.mutation.Quantity(); ok {
		_spec.SetField(book.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedQuantity(); ok {
		_spec.AddField(book.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Rented(); ok {
		_spec.SetField(book.FieldRented, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedRented(); ok {
		_spec.AddField(book.FieldRented, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if buo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedUserIDs(); len(nodes) > 0 && !buo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.UserTable,
			Columns: book.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedCategoryIDs(); len(nodes) > 0 && !buo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: book.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
